/**
 * Landing-page and auth copy in English and Persian.
 *
 * Deliberately NOT using `src/i18n.ts`: the i18n test scans every file under
 * `src/` for translatable string calls and fails when a Persian translation is
 * missing. The marketing site keeps its own typed dictionary instead, and
 * TypeScript checks the `fa` record below for completeness.
 */

export const en = {
  brand: 'Planner',
  tagline: 'calm daily planning',

  navHow: 'How it works',
  navRoles: 'Roles',
  navGuardians: 'For parents',
  navPrivacy: 'Privacy',
  navAI: 'AI',
  navApps: 'Apps',
  navSignIn: 'Sign in',
  navStart: 'Get started',
  navBackHome: 'Back to the site',
  navMenu: 'Menu',
  navClose: 'Close',
  themeToggle: 'Switch theme',
  langToggle: 'Switch language',

  heroKicker: 'Calm planning — alone, or together',
  heroTitle: 'A planner that keeps your day quiet.',
  heroSub:
    'Plan today, see your week, and shape the weeks ahead. Then, if you want it, let a parent or advisor walk beside you — seeing the plan, never the journal.',
  heroCta: 'Start planning — free',
  heroCta2: 'See how it works',
  heroTrust: 'End-to-end encrypted  ·  Works offline  ·  No ads, ever',
  heroDemoStudent: "Today — Sara's planner",
  heroDemoGuardian: "Guardian panel — Sara's week",

  stepsKicker: 'How it works',
  stepsTitle: 'Three steps, and nothing more',
  stepsSub: 'You can stop after step one. Most people do.',
  step1T: 'Pick your role',
  step1D: 'Just me, student, or parent & advisor. Every role lands in the same calm planner.',
  step2T: 'Plan your week',
  step2D: 'Tasks, habits, goals and notes in one place. Ask the AI to draft a week, then edit it.',
  step3T: 'Share what you choose',
  step3D: 'A student accepts a link and decides what each guardian sees. Private stays private.',

  rolesKicker: 'Roles',
  rolesTitle: 'One app, three ways to use it',
  rolesSub: 'Your personal planner never changes. Roles only add a door — you hold the key.',
  rolePersonalTag: 'Most people start here',
  rolePersonalT: 'Personal',
  rolePersonalD: 'Your day, your week, your notes. Nobody else sees a thing.',
  rolePersonalL1: 'Everything in the app today',
  rolePersonalL2: 'Encrypted sync across your devices',
  rolePersonalL3: 'Works offline, no account needed to peek',
  roleStudentT: 'Student',
  roleStudentD: 'Your plans, your report — and a private drawer that stays yours.',
  roleStudentL1: 'Daily, weekly and monthly plans',
  roleStudentL2: 'One-tap reasons when you change a plan',
  roleStudentL3: 'A private zone no guardian can open',
  roleGuardianT: 'Parent & advisor',
  roleGuardianD: 'See how they are really doing, and help without hovering.',
  roleGuardianL1: 'A roster, then one tap into a student',
  roleGuardianL2: 'Charts that explain themselves in one line',
  roleGuardianL3: 'Propose changes instead of silently editing',

  guardianKicker: 'The guardian panel',
  guardianTitle: 'One number, one paragraph, and six charts behind it',
  guardianSub:
    'No dashboard sprawl. You open a student and immediately see how their week is going and what to do about it.',
  guardianHeroLabel: 'This week',
  guardianHeroDelta: 'up 12% on last month',
  guardianNarrative:
    'Sara finished 78% of her plan, up 12% on last month. Her mood dipped on the three days she studied past 10pm. Thursday looks overloaded — consider moving one session.',
  chart1: 'Completion trend',
  chart1d: 'Against their own baseline, not a target.',
  chart2: 'Mood × load',
  chart2d: 'Spots burnout before grades do.',
  chart3: 'Week rhythm',
  chart3d: 'When they actually work.',
  chart4: 'Habit grid',
  chart4d: 'Rest days never break a streak.',
  chart5: 'Plan vs actual',
  chart5d: 'Shows chronic over-planning.',
  chart6: 'Balance',
  chart6d: 'Study, rest, chores, people.',
  guardianFeed: 'Changes this week',
  guardianFeed1Title: 'Moved Math homework to Thursday',
  guardianFeed1Why: 'Too much today',
  guardianFeed1Meta: 'Sara · 2 hours ago',
  guardianFeed2Title: 'Marked Chemistry lab as done',
  guardianFeed2Meta: 'Sara · yesterday',
  guardianFeed3Title: 'Cleared Saturday morning',
  guardianFeed3Why: 'Need help with this one',
  guardianFeed3Meta: 'Sara · Monday',

  studentKicker: 'The student side',
  studentTitle: 'Plans you can actually keep',
  studentSub: 'Simple on purpose: what you planned, what you did, and one button when it is too much.',
  studentL1: 'Daily, weekly and monthly plans in one view',
  studentL2: '"This is too much today" — the AI rebalances and lets your guardian know',
  studentL3: 'Guardian proposals arrive for your approval, never as silent edits',
  studentL4: 'A private drawer for notes nobody else reads',
  studentPrivate: 'Private',

  aiKicker: 'AI on both sides',
  aiTitle: 'It proposes. You decide.',
  aiSub: 'The AI never writes to a plan on its own. Everything it suggests lands as a draft you review.',
  aiStudentT: 'For students',
  aiStudentD:
    '“I cannot do today — make it lighter.” Back-plan a whole term from one exam date. Break a scary assignment into small steps.',
  aiGuardianT: 'For parents & advisors',
  aiGuardianD:
    '“Why is Amir slipping?” — a plain-language answer built from his week. Draft next week, or a note to his parents.',
  aiRule: 'Every suggestion says why. Nothing is applied without a person pressing yes.',

  privacyKicker: 'Privacy',
  privacyTitle: 'Encrypted so completely that we could not read your planner if we tried',
  privacySub: 'The server is a librarian, not a reader. It knows who you are and who you are linked to. Nothing else.',
  privacyCanTitle: 'We can see',
  privacyCan1: 'Your username and email',
  privacyCan2: 'Who you are linked to',
  privacyCan3: 'That a change happened — never what it was',
  privacyCannotTitle: 'We cannot see',
  privacyCannot1: 'A single task, note, mood or reason',
  privacyCannot2: 'Your password or your vault key',
  privacyCannot3: 'Anything after a week folds into results',
  retentionT: 'Your weeks become results, not archives',
  retentionD:
    'While a week is live, every change and reason is kept. After it closes, the detail rolls up into a small summary — a few hundred bytes — and the rest is gone. Your planner stops growing, and old data can never leak.',

  offlineKicker: 'Offline & installed',
  offlineTitle: 'It opens without a signal',
  offlineSub: 'Sign in once. After that your device is trusted and the planner works anywhere.',
  offlineL1: 'Edit, complete and plan with no connection',
  offlineL2: 'Install it on phone, tablet or desktop',
  offlineL3: 'Installed apps can notify you — the website keeps notifications inside the panel',

  faqKicker: 'Good to know',
  faqTitle: 'Questions people ask',
  faq1q: 'Do I need an account?',
  faq1a: 'Yes — one account keeps your planner yours across devices and makes linking to a guardian possible.',
  faq2q: 'Can a parent read my notes?',
  faq2a: 'Only notes you share. Anything you mark private is invisible to every guardian, with no override.',
  faq3q: 'What happens if I forget my password?',
  faq3a:
    'Use a passkey you have already saved, or enter one of the recovery codes from sign-up to set a new password. A trusted device can also reopen your planner without another sign-in.',
  faq4q: 'Is this surveillance?',
  faq4a:
    'No. There is no screen monitoring, no location sharing, no leaderboards. Students see exactly who is watching and what they can see.',
  faq5q: 'How long is my data kept?',
  faq5a:
    'As long as you want. Live weeks keep full detail; closed weeks fold into small summaries you choose the window for.',

  ctaTitle: 'Start with today.',
  ctaSub: 'One quiet page. Add a task, check it off, and see how the week builds.',
  ctaButton: 'Create your planner',
  ctaSecondary: 'Talk to us first',

  footerRights: 'All rights reserved.',
  footerPrivacy: 'Privacy',
  footerTerms: 'Terms',
  footerSecurity: 'Security',
  footerStatus: 'Status',
  footerCode: 'Source',
  footerBuilt: 'Built for calm mornings.',

  authSignInTitle: 'Welcome back',
  authSignInSub: 'Use your username or email and password to continue.',
  authSignUpTitle: 'Create your planner',
  authSignUpSub: 'It takes about a minute. You can add a student or guardian panel now or later.',
  authName: 'Name',
  authNameHint: 'This is the name linked students and guardians will see.',
  authNamePlaceholder: 'The name you go by',
  authUsername: 'Username or email',
  authUsernameOnly: 'Username',
  authUsernameHint: '3–24 characters: English letters, numbers, or underscores.',
  authUsernamePlaceholder: 'name@example.com or username',
  authNewUsernamePlaceholder: 'Choose a username',
  authEmailPlaceholder: 'name@example.com',
  authEmail: 'Email (optional)',
  authEmailHint: 'For security alerts only. Your planner is never sent by email.',
  authPassword: 'Password',
  authPasswordHint: 'At least 10 characters. Choose a long, memorable phrase.',
  authPasswordPlaceholder: 'Enter your password',
  authShow: 'Show password',
  authHide: 'Hide password',
  authCapsLock: 'Caps Lock is on.',
  authRemember: 'Remember this device',
  authRememberHint: 'On a personal device, reopen your planner without entering your password again.',
  authPasskey: 'Continue with a passkey',
  authPasskeyHint: 'Use your fingerprint, face, or device PIN.',
  authPasskeyAdd: 'Add a passkey',
  authPasskeyAddHint: 'Use your fingerprint or face to sign in. On supported devices, a passkey can also unlock your planner without a password.',
  authPasskeyAdded: 'Passkey added ✓',
  authPasskeyBusy: 'Waiting for your passkey…',
  authForgot: 'Forgot your password?',
  authNoAccount: 'New to Planner?',
  authHasAccount: 'Already have an account?',
  authCreate: 'Create an account',
  authSignInAction: 'Sign in',
  authContinue: 'Continue',
  authBack: 'Back',
  authStrengthWeak: 'Too short',
  authStrengthFair: 'Fair',
  authStrengthGood: 'Good',
  authStrengthStrong: 'Strong',
  authStepRole: 'Add a panel? It is optional.',
  authStepRoleSub: 'Your personal planner is always there. Choose a student or guardian panel now, or skip it and add one later from your dashboard.',
  authRolePersonal: 'Personal planner',
  authRolePersonalD: 'Start with your own planner. Add a panel whenever you are ready.',
  authRoleStudent: 'Student panel',
  authRoleStudentD: 'Keep track of subjects, exams, and a weekly summary.',
  authRoleGuardian: 'Guardian panel',
  authRoleGuardianD: 'Follow students and see the weekly results they choose to share.',
  authRoleSkip: 'Skip for now — use my personal planner',
  authRoleMissing: 'Add the details for the panel you chose, or skip for now.',
  authStudentField: 'What are you studying?',
  authStudentFieldHint: 'One line is enough: Physics, Law, Design…',
  authStudentGrade: 'What is your current level?',
  authChooseGrade: 'Choose your level',
  authGuardianField: 'What subject or course do you support?',
  authGuardianFieldHint: 'For example, maths, science, or a college course.',
  authGrade9: 'Grade 9',
  authGrade10: 'Grade 10',
  authGrade11: 'Grade 11',
  authGrade12: 'Grade 12',
  authGradeUniversity: 'University',
  authGradePostgrad: 'Master’s or PhD',
  authGradeOther: 'Other',
  authRoleKind: 'Which best describes you?',
  authRoleKindParent: 'Parent or guardian',
  authRoleKindParentD: 'Following my own children.',
  authRoleKindAdvisor: 'School advisor',
  authRoleKindAdvisorD: 'Supporting students I work with.',
  authRecoveryTitle: 'Save your recovery codes',
  authRecoverySub:
    'Each of these codes opens your planner on its own, so keep them for the day you forget your password and cannot use a trusted device or passkey. Any one of them will do. We cannot recover lost codes: copy or download them and keep them somewhere private.',
  authRecoveryCopy: 'Copy all codes',
  authRecoveryCopied: 'Copied',
  authRecoveryDownload: 'Download codes',
  authRecoveryPrint: 'Print codes',
  authRecoverySaved: 'I have saved these codes somewhere safe',
  authRecoveryView: 'For your security, these codes are shown only once.',
  authRecoveryWarn: 'Each code unlocks your encrypted planner by itself. Anyone who finds one can open your planner.',
  authRecoveryConfirmLabel: 'Type code {n} to confirm you have saved it',
  authRecoveryConfirmHint: 'Look at the list above and type the code numbered {n}. We ask because these codes cannot be shown again.',
  authRecoveryConfirmOk: 'That matches. You are ready to continue.',
  authRecoveryConfirmBad: 'That is not code {n}. Check the number above and try again.',
  authTotpTitle: 'One more step',
  authTotpSub: 'Enter the six-digit code your authenticator app is showing. It changes every 30 seconds.',
  authTotpLabel: 'Code from your app',
  authTotpContinue: 'Finish signing in',
  authTotpBack: 'Start again',
  authTotpWrong: 'That code is not right, or has already been used. Wait for the next one and try again.',
  authRecoverTitle: 'Reset your password',
  authRecoverSub: 'Enter your username or email, one of your recovery codes, and a new password to regain access to your encrypted planner.',
  authRecoverPasskey: 'Try a passkey instead',
  authRecoverPasskeyD: 'If you saved a passkey, use it to sign in. You may still need your password to unlock your planner.',
  authRecoverKeyD: 'Enter any one of the 20-character codes you saved when you created your account.',
  authRecoverKeyLabel: 'Recovery code',
  authRecoverKeyPlaceholder: 'plnr-••••-••••-••••-••••',
  authRecoverIdentifier: 'Username or email',
  authRecoverNewPassword: 'New password',
  authRecoverConfirm: 'Confirm new password',
  authRecoverReset: 'Reset password',
  authRecoverResetting: 'Checking your recovery code…',
  authRecoveryInvalid: 'That username or email and recovery code do not match. Check both and try again.',
  authPasswordMismatch: 'The passwords do not match.',
  authRecoveryCompleteTitle: 'Password updated',
  authRecoveryCompleteSub:
    'The code you used is spent, so here is a fresh set. Save these new codes somewhere safe, then sign in with your new password.',
  authRecoveryComplete: 'Back to sign in',
  authRecoverBack: 'Back to sign in',
  authTerms: 'I agree to the Terms and the Privacy Policy.',
  shotWeek: 'Sunday evening, ten minutes, and the week is set.',
  shotAI: 'It reads the week ahead — never your diary.',
  shotDevices: 'Phone in the kitchen, tablet at the desk, laptop at work: the same week, everywhere.',

  linkKicker: 'For parents and advisors',
  linkTitle: 'One code, typed once.',
  linkSub:
    'A guardian asks to follow you, and gets a code worth giving in person. You type it once in your own panel. After that, your weekly results find their way to them on their own.',
  link1T: 'They ask',
  link1D: 'A parent or advisor adds your username and gets a code to hand over.',
  link2T: 'You accept',
  link2D: 'Type the code once. It opens a key that only the two of you hold — the server never sees it.',
  link3T: 'Results travel',
  link3D: 'Each week, how much you planned, how much you finished, how long you focused, and the headline you wrote.',
  link4T: 'They understand',
  link4D: 'Charts over the last twelve weeks, and a few questions worth asking instead of a pile of detail.',
  linkNote: 'Only results travel. Never a task, never a note, never a reason you did not choose to send.',
  linkGuardianT: 'Two adults, one student',
  linkGuardianD:
    'A parent and an advisor are different roles. When one of them changes something for a student, the student’s own planner passes the word to the other — still encrypted, still in the app.',

  authGoToApp: 'Open my planner',
  authOr: 'or',
  authQuote1: 'I stopped arguing about homework. We just look at the week together.',
  authQuote1By: 'Parent of a 15-year-old',
  authQuote2: 'The private drawer is the reason I actually use it.',
  authQuote2By: 'Student, first year',
  authQuote3: 'One code, typed once — and then the weeks just arrive.',
  authQuote3By: 'Advisor, sixth form',
  authBusy: 'Securing your planner',
  errBadCredentials: 'Wrong username or password.',
  errTaken: 'That username is already taken.',
  errEmailTaken: 'That email is already registered.',
  errNotConfigured: 'Accounts are not set up on this server yet.',
  errNetwork: 'Could not reach the server. Check your connection.',
  errDeploymentGate:
    'This deployment is behind a hosting sign-in page, so the app cannot reach its own API. Turn off Vercel Authentication (Project Settings → Deployment Protection), or open the production domain, then try again.',
  errApiMissing:
    'The accounts API did not answer at this address. Redeploy the app with its api/ functions, or check the domain you are using, then try again.',
  errLocalOnly:
    'This copy of Planner was built for offline use, with no server address, so there is nothing to sign in to. Your planner still works on this device.',
  errAppOriginRefused:
    'The server is answering, but it refuses requests from the app’s own origin, so signing in cannot work yet. The deployed server needs the packaged apps in PLANNER_APP_ORIGINS (docs/APPS.md, section 2); nothing on this device is lost meanwhile.',
  errTemporaryAccounts:
    'Accounts on this server are kept in memory only, so restarting it signs everyone out. Add a DATABASE_URL to keep them.',
  errPasskeyCancelled: 'Passkey sign-in was cancelled.',
  errPasskeyUnsupported: 'Passkeys need a modern browser on a secure connection.',
  errPasskeyNoPrf: "This browser's passkeys cannot open your planner — your password will.",
  errPasskeySession: 'Sign in first, then add a passkey.',
  errPasskeyRejected: 'That passkey was not accepted on this account.',
  errRateLimited: 'Too many attempts. Wait a minute, then try again.',
  errUnexpectedResponse: 'The server returned an unexpected response. Please try again.',
  errUnknown: 'Something went wrong. Please try again.',
  errShortPassword: 'Use at least 10 characters.',
  errNameRules: 'Please enter a name — up to 60 characters.',
  errUsernameRules: 'Use 3–24 characters: English letters, numbers, or underscores.',
  errEmailRules: 'That email address does not look right.',

  navBadge: 'New',
  heroBadge: 'Now with shared planning',
  heroTitleLead: 'A planner that keeps',
  heroTitleAccent: 'your day quiet.',
  trustEncrypted: 'End-to-end encrypted',
  trustOffline: 'Works offline',
  trustAds: 'No ads, ever',
  heroNote: 'Nothing here leaves your device unencrypted',
  strip1: 'End-to-end encrypted',
  strip2: 'Works offline on every device',
  strip3: 'Students keep a private drawer',
  strip4: 'Closed weeks fold into results',
  strip5: 'Export everything, any time',
  appWinTitle: 'Planner',
  appWinTab: 'Today',
  heroStat1: '78% this week',
  heroStat2: '12-day streak',
  heroStat3: '2 changes today',
  heroCardTitle: 'Sara moved Math homework',
  heroCardWhy: 'Too much today',
  heroCardMeta: 'Just now',
  roleTabPersonal: 'Just me',
  roleTabStudent: 'Student',
  roleTabGuardian: 'Guardian',
  switcherKicker: 'Try the roles',
  switcherTitle: 'Three doors, one planner',
  switcherSub: 'Switch between them to see what each person actually sees.',
  previewPersonalTitle: 'Just me',
  previewPersonalBody: 'Nine quiet pages. Tasks, habits, goals, notes, insights — and nobody else in the room.',
  previewPersonalTag: 'Nothing is shared',
  previewStudentTitle: 'Student',
  previewStudentBody: 'The same planner, plus one card showing who is watching and what they can see.',
  previewStudentTag: 'You choose what is shared',
  previewGuardianTitle: 'Parent & advisor',
  previewGuardianBody: 'A roster instead of your own week. One number, one paragraph, and the changes behind them.',
  previewGuardianTag: 'You see their week',
  matrixKicker: 'Who sees what',
  matrixTitle: 'Nothing is visible by accident',
  matrixSub: 'Every cell here is a choice the student makes when they accept a link.',
  matrixColOwner: 'The student',
  matrixColParent: 'A parent',
  matrixColAdvisor: 'An advisor',
  matrixRowPlan: 'Tasks and plans',
  matrixRowHabit: 'Habits and streaks',
  matrixRowMood: 'Mood check-ins',
  matrixRowNote: 'Notes and journals',
  matrixRowFocus: 'Focus time',
  matrixRowDeadline: 'Deadlines and subjects',
  matrixYes: 'Visible',
  matrixNo: 'Never visible',
  matrixOpt: 'Only if shared',
  dashKicker: 'The guardian panel',
  dashTitle: 'It builds itself as you look',
  dashS1T: 'One number',
  dashS1D: 'How the week is going against their own baseline.',
  dashS2T: 'One paragraph',
  dashS2D: 'What changed, and what to do about it — written from the data.',
  dashS3T: 'Six charts',
  dashS3D: 'Only when you want the detail. Each one says why it matters.',
  aiApprove: 'Approve',
  aiDecline: 'Not now',
  aiApproved: 'Added to the plan',
  aiProposal: 'Move Math homework to Thursday',
  aiProposalWhy: 'Thursday has two free hours; Tuesday already has six.',
  aiProposalBy: 'Suggested by AI',
  retSliderLabel: 'Keep full detail for',
  retWeeks: 'weeks',
  retForever: 'Forever',
  retAfter: 'after the week closes',
  retResults: 'results only',
  retSize: 'about 25 KB per year of history',
  statsKicker: 'By the numbers',
  statsTitle: 'Small promises, kept',
  stat1v: '0',
  stat1l: 'Ads, trackers, or data sold',
  stat2v: '100%',
  stat2l: 'Of planner content encrypted',
  stat3v: '25 KB',
  stat3l: 'Of history kept per year',
  stat4v: '3',
  stat4l: 'Ways back in if you forget',
  quotesKicker: 'Early words',
  quotesTitle: 'What people say',
  quote3: 'I can see he is drowning before he tells me. That changed everything.',
  quote3By: 'Mother of a first-year student',
  footProduct: 'Product',
  footCompany: 'Company',
  footLegal: 'Legal',
  footTour: 'Take the tour',
  footPricing: 'Pricing',
  footChangelog: 'What is new',
  footAbout: 'About',
  footContact: 'Contact',
  footGithub: 'Source',
  ctaBadge: 'Free to start',
  platformsKicker: 'Everywhere you plan',
  platformsTitle: 'On your phone, your laptop, your desktop',
  platformsSub:
    'The same calm planner, installed like an app. Everything stays on the device, and syncs only when you ask it to.',
  platformsIphone: 'iPhone and iPad',
  platformsIphoneNote:
    'In Safari, Share → Add to Home Screen installs the whole planner with its own icon. The App Store listing follows.',
  platformsAndroid: 'Android',
  platformsAndroidNote:
    'The APK installs on any Android phone — Xiaomi, Redmi, Samsung, Pixel, Huawei — and updates from the same place. Store listings follow.',
  platformsWindows: 'Windows',
  platformsWindowsNote:
    'An installer for Windows 10 and 11 with a Start-menu shortcut, for Intel/AMD and ARM PCs alike.',
  platformsMac: 'macOS',
  platformsMacNote: 'A disk image for Apple silicon and Intel Macs.',
  platformsLinux: 'Linux',
  platformsLinuxNote: 'AppImage, .deb and .rpm — no repository, no root.',
  platformsDownloadWindows: 'Download for Windows',
  platformsDownloadMacArm: 'Download for Apple silicon',
  platformsDownloadMacIntel: 'Download for Intel Macs',
  platformsDownloadApk: 'Download the APK',
  platformsDownloadLinuxAppImage: 'AppImage (x86_64)',
  platformsDownloadLinuxDeb: '.deb (x86_64)',
  platformsDownloadLinuxRpm: '.rpm (x86_64)',
  platformsDownloadLinuxArmImage: 'AppImage (ARM64)',
  platformsDownloadLinuxArmDeb: '.deb (ARM64)',
  platformsSeeOptions: 'See install options',
  platformsAllReleases: 'All releases',
  platformsDownloadFoot: 'Saves the file straight from this page. Hosted on GitHub Releases.',
  platformsSource: 'Build from source',
  platformsAppStore: 'App Store',
  platformsPlayStore: 'Google Play',
  platformsWebInstead: 'Use the web app',
  platformsHere: 'This device',
  platformsAlsoOn: 'Also on',
  platformsFoot:
    'Every build is the same planner, and the web app always works without installing anything.',
} as const;

export const fa: Record<keyof typeof en, string> = {
  brand: 'پلنر',
  tagline: 'برنامه‌ریزی آرام روزانه',

  navHow: 'چطور کار می‌کند',
  navRoles: 'نقش‌ها',
  navGuardians: 'برای والدین',
  navPrivacy: 'حریم خصوصی',
  navApps: 'برنامه‌ها',
  navAI: 'هوش مصنوعی',
  navSignIn: 'ورود',
  navStart: 'شروع کنید',
  navBackHome: 'بازگشت به وب‌سایت',
  navMenu: 'منو',
  navClose: 'بستن',
  themeToggle: 'تغییر پوسته',
  langToggle: 'تغییر زبان',

  heroKicker: 'برنامه‌ریزی آرام — تنها یا با هم',
  heroTitle: 'برنامه‌ریزی‌ای که روزتان را آرام نگه می‌دارد.',
  heroSub:
    'امروز، هفته و هفته‌های پیشِ رو را برنامه بریزید. بعد، اگر خواستید، اجازه دهید والد یا مشاور کنارتان باشد — برنامه را ببیند، نه دفترچه‌تان را.',
  heroCta: 'شروع کنید — رایگان',
  heroCta2: 'ببینید چطور کار می‌کند',
  heroTrust: 'رمزنگاری سرتاسری  ·  کار آفلاین  ·  بدون تبلیغ',
  heroDemoStudent: 'امروز — برنامهٔ سارا',
  heroDemoGuardian: 'پنل سرپرست — هفتهٔ سارا',

  stepsKicker: 'چطور کار می‌کند',
  stepsTitle: 'سه قدم، و نه بیشتر',
  stepsSub: 'می‌توانید همان قدم اول تمام کنید. بیشتر افراد همین کار را می‌کنند.',
  step1T: 'نقش‌تان را انتخاب کنید',
  step1D: 'فقط خودم، دانش‌آموز، یا والد و مشاور. همه به یک برنامه‌ریز آرام می‌رسند.',
  step2T: 'هفته‌تان را برنامه بریزید',
  step2D: 'کارها، عادت‌ها، هدف‌ها و یادداشت‌ها در یک جا. از هوش مصنوعی بخواهید پیش‌نویس بزند، بعد خودتان ویرایش کنید.',
  step3T: 'هرچه می‌خواهید به اشتراک بگذارید',
  step3D: 'دانش‌آموز پیوند را می‌پذیرد و تعیین می‌کند هر سرپرست چه ببیند. خصوصی، خصوصی می‌ماند.',

  rolesKicker: 'نقش‌ها',
  rolesTitle: 'یک برنامه، سه شیوهٔ استفاده',
  rolesSub: 'برنامهٔ شخصی‌تان هرگز تغییر نمی‌کند. نقش‌ها فقط یک در اضافه می‌کنند — کلید دست خودتان است.',
  rolePersonalTag: 'بیشتر افراد از اینجا شروع می‌کنند',
  rolePersonalT: 'شخصی',
  rolePersonalD: 'روزتان، هفته‌تان، یادداشت‌هایتان. هیچ‌کس چیزی نمی‌بیند.',
  rolePersonalL1: 'همهٔ چیزی که امروز در برنامه هست',
  rolePersonalL2: 'همگام‌سازی رمزنگاری‌شده بین دستگاه‌ها',
  rolePersonalL3: 'آفلاین کار می‌کند',
  roleStudentT: 'دانش‌آموز',
  roleStudentD: 'برنامه‌ها و گزارش خودتان — و یک کشوی خصوصی که مال خودتان می‌ماند.',
  roleStudentL1: 'برنامه‌های روزانه، هفتگی و ماهانه',
  roleStudentL2: 'دلیل تغییر با یک لمس',
  roleStudentL3: 'یک بخش خصوصی که هیچ سرپرستی نمی‌تواند باز کند',
  roleGuardianT: 'والد و مشاور',
  roleGuardianD: 'ببینید واقعاً چطور پیش می‌روند، بدون اینکه بالای سرشان باشید.',
  roleGuardianL1: 'فهرست دانش‌آموزان، بعد یک لمس تا صفحهٔ هر کدام',
  roleGuardianL2: 'نمودارهایی که در یک خط خودشان را توضیح می‌دهند',
  roleGuardianL3: 'پیشنهاد تغییر، نه ویرایش پنهانی',

  guardianKicker: 'پنل سرپرست',
  guardianTitle: 'یک عدد، یک پاراگراف، و شش نمودار پشتِ آن',
  guardianSub: 'بدون شلوغی داشبورد. صفحهٔ دانش‌آموز را باز می‌کنید و همان لحظه می‌بینید هفته‌اش چطور است و چه باید کرد.',
  guardianHeroLabel: 'این هفته',
  guardianHeroDelta: '۱۲٪ بهتر از ماه قبل',
  guardianNarrative:
    'سارا ۷۸٪ برنامه‌اش را انجام داده، ۱۲٪ بهتر از ماه قبل. در سه روزی که بعد از ساعت ۱۰ شب درس خوانده حالش افت کرده. پنجشنبه سنگین به نظر می‌رسد — یکی از جلسه‌ها را جابه‌جا کنید.',
  chart1: 'روند انجام کارها',
  chart1d: 'در مقایسه با روند خودش، نه یک هدف تحمیلی.',
  chart2: 'حال × حجم کار',
  chart2d: 'فرسودگی را زودتر از نمره‌ها نشان می‌دهد.',
  chart3: 'ریتم هفته',
  chart3d: 'واقعاً کی کار می‌کند.',
  chart4: 'شبکهٔ عادت‌ها',
  chart4d: 'روز استراحت، رشته را نمی‌شکند.',
  chart5: 'برنامه در برابر واقعیت',
  chart5d: 'برنامه‌ریزی بیش‌از‌اندازه را نشان می‌دهد.',
  chart6: 'توازن',
  chart6d: 'درس، استراحت، خانه، آدم‌ها.',
  guardianFeed: 'تغییرهای این هفته',
  guardianFeed1Title: 'تکلیف ریاضی به پنجشنبه منتقل شد',
  guardianFeed1Why: 'امروز کارم زیاد است',
  guardianFeed1Meta: 'سارا · ۲ ساعت پیش',
  guardianFeed2Title: 'آزمایش شیمی انجام شد',
  guardianFeed2Meta: 'سارا · دیروز',
  guardianFeed3Title: 'صبح شنبه خالی شد',
  guardianFeed3Why: 'برای این یکی کمک می‌خواهم',
  guardianFeed3Meta: 'سارا · دوشنبه',

  studentKicker: 'سمت دانش‌آموز',
  studentTitle: 'برنامه‌هایی که واقعاً می‌شود نگه داشت',
  studentSub: 'به‌عمد ساده: چه برنامه ریختید، چه انجام دادید، و یک دکمه وقتی کار زیاد است.',
  studentL1: 'برنامه‌های روزانه، هفتگی و ماهانه در یک نما',
  studentL2: '«امروز زیاد است» — هوش مصنوعی دوباره تنظیم می‌کند و به سرپرست خبر می‌دهد',
  studentL3: 'پیشنهادهای سرپرست برای تأیید شما می‌آیند، نه به‌صورت ویرایش پنهان',
  studentL4: 'یک کشوی خصوصی برای یادداشت‌هایی که کسی نمی‌خواند',
  studentPrivate: 'خصوصی',

  aiKicker: 'هوش مصنوعی در هر دو سمت',
  aiTitle: 'پیشنهاد می‌دهد. تصمیم با شماست.',
  aiSub: 'هوش مصنوعی هیچ‌وقت خودش در برنامه چیزی نمی‌نویسد. هر پیشنهاد به‌صورت پیش‌نویس می‌آید تا شما بخوانید.',
  aiStudentT: 'برای دانش‌آموز',
  aiStudentD:
    '«امروز نمی‌توانم — سبک‌ترش کن.» از یک تاریخ امتحان، کل ترم را برنامه بریز. یک تکلیف ترسناک را به قدم‌های کوچک تقسیم کن.',
  aiGuardianT: 'برای والدین و مشاوران',
  aiGuardianD:
    '«چرا امیر عقب افتاده؟» — پاسخی ساده که از هفته‌اش ساخته شده. پیش‌نویس هفتهٔ بعد، یا یادداشتی برای والدینش.',
  aiRule: 'هر پیشنهاد دلیلش را می‌گوید. هیچ چیز بدون تأیید شما اعمال نمی‌شود.',

  privacyKicker: 'حریم خصوصی',
  privacyTitle: 'آن‌قدر رمزنگاری‌شده که اگر هم می‌خواستیم نمی‌توانستیم برنامه‌تان را بخوانیم',
  privacySub: 'سرور یک کتابدار است، نه خواننده. می‌داند شما کیستید و به چه کسی پیوند خورده‌اید. بس.',
  privacyCanTitle: 'می‌توانیم ببینیم',
  privacyCan1: 'نام کاربری و ایمیل شما',
  privacyCan2: 'به چه کسی پیوند خورده‌اید',
  privacyCan3: 'اینکه تغییری رخ داده — نه اینکه چه بوده',
  privacyCannotTitle: 'نمی‌توانیم ببینیم',
  privacyCannot1: 'حتی یک کار، یادداشت، حال یا دلیل',
  privacyCannot2: 'رمز عبور یا کلید گاوصندوق شما',
  privacyCannot3: 'چیزی که بعد از بسته شدن هفته به خلاصه تبدیل شده',
  retentionT: 'هفته‌های شما به نتیجه تبدیل می‌شوند، نه بایگانی',
  retentionD:
    'تا وقتی هفته زنده است، همهٔ تغییرها و دلیل‌ها نگه داشته می‌شود. وقتی بسته می‌شود، جزئیات در یک خلاصهٔ کوچک — چندصد بایت — جمع می‌شود و بقیه می‌رود. برنامه‌تان دیگر بزرگ نمی‌شود و دادهٔ قدیمی هرگز نشت نمی‌کند.',

  offlineKicker: 'آفلاین و نصب‌شده',
  offlineTitle: 'بدون آنتن هم باز می‌شود',
  offlineSub: 'یک بار وارد شوید. بعد از آن دستگاه‌تان معتمد است و برنامه هر جا کار می‌کند.',
  offlineL1: 'بدون اتصال، ویرایش و برنامه‌ریزی کنید',
  offlineL2: 'روی موبایل، تبلت یا رایانه نصبش کنید',
  offlineL3: 'برنامهٔ نصب‌شده می‌تواند آگاه‌سازی بفرستد — نسخهٔ وب آگاه‌سازی را داخل پنل نگه می‌دارد',

  faqKicker: 'بدانید',
  faqTitle: 'سؤال‌هایی که معمولاً پرسیده می‌شود',
  faq1q: 'به حساب کاربری نیاز دارم؟',
  faq1a: 'بله — یک حساب، برنامه‌تان را در همهٔ دستگاه‌ها مال شما نگه می‌دارد و پیوند با سرپرست را ممکن می‌کند.',
  faq2q: 'والدینم می‌توانند یادداشت‌هایم را بخوانند؟',
  faq2a: 'فقط یادداشت‌هایی که خودتان به اشتراک گذاشته‌اید. هرچه را خصوصی علامت بزنید برای همهٔ سرپرست‌ها نامرئی است.',
  faq3q: 'اگر رمز عبورم را فراموش کنم چه؟',
  faq3a:
    'با کلید عبوری که قبلاً ثبت کرده‌اید وارد شوید؛ یا یکی از کدهای بازیابی زمان ساخت حساب را وارد کنید و رمز تازه بسازید. دستگاه مورداعتماد هم می‌تواند برنامه را بدون ورود دوباره باز کند.',
  faq4q: 'این نظارت نیست؟',
  faq4a:
    'نه. پایش صفحه نداریم، مکان‌یابی نداریم، رتبه‌بندی نداریم. دانش‌آموز دقیقاً می‌بیند چه کسی نگاه می‌کند و چه چیزی می‌بیند.',
  faq5q: 'داده‌هایم چقدر نگه داشته می‌شود؟',
  faq5a:
    'هرقدر بخواهید. هفتهٔ جاری جزئیات کامل دارد؛ هفته‌های بسته‌شده به خلاصه‌های کوچکی تبدیل می‌شوند که بازه‌اش دست خودتان است.',

  ctaTitle: 'از امروز شروع کنید.',
  ctaSub: 'یک صفحهٔ آرام. یک کار اضافه کنید، انجامش را بزنید و ببینید هفته چطور ساخته می‌شود.',
  ctaButton: 'برنامه‌ام را بسازم',
  ctaSecondary: 'اول با ما صحبت کنید',

  footerRights: 'همهٔ حقوق محفوظ است.',
  footerPrivacy: 'حریم خصوصی',
  footerTerms: 'شرایط',
  footerSecurity: 'امنیت',
  footerStatus: 'وضعیت',
  footerCode: 'کد منبع',
  footerBuilt: 'ساخته‌شده برای صبح‌های آرام.',

  authSignInTitle: 'خوش برگشتید',
  authSignInSub: 'برای ادامه، نام کاربری یا ایمیل و رمز عبورتان را وارد کنید.',
  authSignUpTitle: 'ساخت حساب کاربری',
  authSignUpSub: 'حدود یک دقیقه طول می‌کشد. می‌توانید پنل دانش‌آموز یا سرپرست را همین حالا یا بعداً اضافه کنید.',
  authName: 'نام نمایشی',
  authNameHint: 'این نام برای افرادی که با آن‌ها در ارتباطید نمایش داده می‌شود.',
  authNamePlaceholder: 'نامی که با آن شناخته می‌شوید',
  authUsername: 'نام کاربری یا ایمیل',
  authUsernameOnly: 'نام کاربری',
  authUsernameHint: '۳ تا ۲۴ نویسه؛ فقط حروف انگلیسی، عدد و زیرخط (_).',
  authUsernamePlaceholder: 'name@example.com یا نام کاربری',
  authNewUsernamePlaceholder: 'یک نام کاربری انتخاب کنید',
  authEmailPlaceholder: 'name@example.com',
  authEmail: 'ایمیل (اختیاری)',
  authEmailHint: 'فقط برای هشدارهای امنیتی؛ محتوای برنامه‌تان با ایمیل فرستاده نمی‌شود.',
  authPassword: 'رمز عبور',
  authPasswordHint: 'حداقل ۱۰ نویسه؛ یک عبارت طولانی و به‌یادماندنی انتخاب کنید.',
  authPasswordPlaceholder: 'رمز عبورتان را وارد کنید',
  authShow: 'نمایش رمز عبور',
  authHide: 'پنهان کردن رمز عبور',
  authCapsLock: 'کلید Caps Lock روشن است.',
  authRemember: 'این دستگاه را به خاطر بسپار',
  authRememberHint: 'روی دستگاه شخصی، دفعهٔ بعد بدون واردکردن دوبارهٔ رمز عبور برنامه را باز کنید.',
  authPasskey: 'ورود با کلید عبور',
  authPasskeyHint: 'با اثر انگشت، تشخیص چهره یا رمز دستگاه وارد شوید.',
  authPasskeyAdd: 'افزودن کلید عبور',
  authPasskeyAddHint: 'با اثر انگشت یا تشخیص چهره وارد شوید. در دستگاه‌های پشتیبانی‌شده، کلید عبور برنامه را هم بدون رمز باز می‌کند.',
  authPasskeyAdded: 'کلید عبور افزوده شد ✓',
  authPasskeyBusy: 'در انتظار تأیید کلید عبور…',
  authForgot: 'رمز عبورتان را فراموش کرده‌اید؟',
  authNoAccount: 'تازه به پلنر آمده‌اید؟',
  authHasAccount: 'از قبل حساب دارید؟',
  authCreate: 'ساخت حساب',
  authSignInAction: 'ورود',
  authContinue: 'ادامه',
  authBack: 'بازگشت',
  authStrengthWeak: 'خیلی کوتاه',
  authStrengthFair: 'متوسط',
  authStrengthGood: 'خوب',
  authStrengthStrong: 'قوی',
  authStepRole: 'پنلی هم می‌خواهید؟ (اختیاری)',
  authStepRoleSub: 'برنامهٔ شخصی‌تان همیشه باقی می‌ماند. پنل دانش‌آموز یا سرپرست را همین حالا انتخاب کنید یا بعداً از پیشخوان اضافه کنید.',
  authRolePersonal: 'برنامهٔ شخصی',
  authRolePersonalD: 'با برنامهٔ خودتان شروع کنید؛ هر زمان خواستید پنلی اضافه کنید.',
  authRoleStudent: 'پنل دانش‌آموز',
  authRoleStudentD: 'درس‌ها، امتحان‌ها و خلاصهٔ هفتگی را دنبال کنید.',
  authRoleGuardian: 'پنل سرپرست',
  authRoleGuardianD: 'دانش‌آموزان را دنبال کنید و نتیجه‌هایی را ببینید که با شما به اشتراک می‌گذارند.',
  authRoleSkip: 'فعلاً رد می‌کنم — فقط از برنامهٔ شخصی استفاده می‌کنم',
  authRoleMissing: 'جزئیات پنل انتخابی را بنویسید یا فعلاً از این مرحله بگذرید.',
  authStudentField: 'چه رشته‌ای می‌خوانید؟',
  authStudentFieldHint: 'یک خط کافی است؛ مثلاً فیزیک، حقوق یا طراحی.',
  authStudentGrade: 'مقطع تحصیلی',
  authChooseGrade: 'مقطع تحصیلی را انتخاب کنید',
  authGuardianField: 'در چه درس یا دوره‌ای کمک می‌کنید؟',
  authGuardianFieldHint: 'مثلاً ریاضی، علوم یا یک درس دانشگاهی.',
  authGrade9: 'پایهٔ نهم',
  authGrade10: 'پایهٔ دهم',
  authGrade11: 'پایهٔ یازدهم',
  authGrade12: 'پایهٔ دوازدهم',
  authGradeUniversity: 'دانشگاه',
  authGradePostgrad: 'کارشناسی ارشد یا دکتری',
  authGradeOther: 'سایر',
  authRoleKind: 'کدام گزینه شما را بهتر توصیف می‌کند؟',
  authRoleKindParent: 'والد یا سرپرست',
  authRoleKindParentD: 'پیگیر وضعیت فرزندان خودم هستم.',
  authRoleKindAdvisor: 'مشاور تحصیلی',
  authRoleKindAdvisorD: 'از دانش‌آموزانی که با آن‌ها کار می‌کنم پشتیبانی می‌کنم.',
  authRecoveryTitle: 'کدهای بازیابی را ذخیره کنید',
  authRecoverySub:
    'هر یک از این کدها به‌تنهایی برنامهٔ شما را باز می‌کند؛ آن‌ها را برای روزی نگه دارید که رمزتان را فراموش کنید و به دستگاه مورداعتماد یا کلید عبور دسترسی نداشته باشید. هر کدام را که بخواهید می‌توانید استفاده کنید. ما نمی‌توانیم کدهای گم‌شده را بازگردانیم: آن‌ها را کپی یا دانلود کنید و در جای امنی نگه دارید.',
  authRecoveryCopy: 'کپی همهٔ کدها',
  authRecoveryCopied: 'کپی شد',
  authRecoveryDownload: 'دانلود کدها',
  authRecoveryPrint: 'چاپ کدها',
  authRecoverySaved: 'این کدها را در جای امنی ذخیره کردم',
  authRecoveryView: 'برای امنیت شما، این کدها فقط همین‌بار نمایش داده می‌شوند.',
  authRecoveryWarn: 'هر کد به‌تنهایی برنامهٔ رمزنگاری‌شدهٔ شما را باز می‌کند. هرکس یکی از آن‌ها را پیدا کند، می‌تواند برنامه‌تان را باز کند.',
  authRecoveryConfirmLabel: 'برای تأیید، کد شمارهٔ {n} را وارد کنید',
  authRecoveryConfirmHint: 'به فهرست بالا نگاه کنید و کد شمارهٔ {n} را بنویسید. این پرسش را می‌پرسیم چون این کدها دیگر نمایش داده نمی‌شوند.',
  authRecoveryConfirmOk: 'درست است. آمادهٔ ادامه هستید.',
  authRecoveryConfirmBad: 'این کد شمارهٔ {n} نیست. شمارهٔ بالا را دوباره بررسی کنید.',
  authTotpTitle: 'یک گام دیگر',
  authTotpSub: 'کد شش‌رقمی را که برنامهٔ تأیید شما نشان می‌دهد وارد کنید. این کد هر ۳۰ ثانیه عوض می‌شود.',
  authTotpLabel: 'کد برنامهٔ شما',
  authTotpContinue: 'پایان ورود',
  authTotpBack: 'شروع دوباره',
  authTotpWrong: 'این کد درست نیست یا قبلاً استفاده شده است. منتظر کد بعدی بمانید و دوباره تلاش کنید.',
  authRecoverTitle: 'بازنشانی رمز عبور',
  authRecoverSub: 'نام کاربری یا ایمیل، یکی از کدهای بازیابی و رمز جدید را وارد کنید تا دوباره به برنامهٔ رمزنگاری‌شده‌تان دسترسی پیدا کنید.',
  authRecoverPasskey: 'ورود با کلید عبور را امتحان کنید',
  authRecoverPasskeyD: 'اگر قبلاً کلید عبور ثبت کرده‌اید، با آن وارد شوید. شاید برای بازکردن برنامه هنوز به رمز عبور نیاز داشته باشید.',
  authRecoverKeyD: 'هر یک از کدهای ۲۰ نویسه‌ای را که هنگام ساخت حساب ذخیره کردید وارد کنید.',
  authRecoverKeyLabel: 'کد بازیابی',
  authRecoverKeyPlaceholder: 'plnr-••••-••••-••••-••••',
  authRecoverIdentifier: 'نام کاربری یا ایمیل',
  authRecoverNewPassword: 'رمز عبور جدید',
  authRecoverConfirm: 'تکرار رمز عبور جدید',
  authRecoverReset: 'بازنشانی رمز عبور',
  authRecoverResetting: 'در حال بررسی کد بازیابی…',
  authRecoveryInvalid: 'این نام کاربری یا ایمیل با کد بازیابی مطابقت ندارد. هر دو را بررسی و دوباره تلاش کنید.',
  authPasswordMismatch: 'رمزهای عبور یکسان نیستند.',
  authRecoveryCompleteTitle: 'رمز عبور تغییر کرد',
  authRecoveryCompleteSub:
    'کدی که استفاده کردید از کار افتاد، بنابراین این مجموعهٔ تازه را دارید. این کدهای جدید را در جای امنی ذخیره کنید و سپس با رمز تازه وارد شوید.',
  authRecoveryComplete: 'بازگشت به ورود',
  authRecoverBack: 'بازگشت به ورود',
  authTerms: 'شرایط و سیاست حریم خصوصی را می‌پذیرم.',
  shotWeek: 'یکشنبه شب، ده دقیقه، و هفته چیده می‌شود.',
  shotAI: 'هفته‌ی پیش‌رو را می‌خواند — هرگز دفتر خاطرات شما را.',
  shotDevices: 'گوشی در آشپزخانه، تبلت روی میز، لپ‌تاپ سر کار: یک هفته، همه‌جا.',

  linkKicker: 'برای والدین و مشاوران',
  linkTitle: 'یک کد، یک‌بار.',
  linkSub:
    'سرپرست درخواست می‌دهد همراه‌تان باشد و کدی می‌گیرد که ارزش دارد حضوری بدهد. شما یک‌بار آن را در پنل خودتان وارد می‌کنید. از آن پس نتایج هفتگی‌تان خودبه‌خود به دست‌شان می‌رسد.',
  link1T: 'آن‌ها درخواست می‌دهند',
  link1D: 'والد یا مشاور نام کاربری شما را اضافه می‌کند و کدی می‌گیرد که به شما بدهد.',
  link2T: 'شما می‌پذیرید',
  link2D: 'کد را یک‌بار وارد می‌کنید. این کلیدی را باز می‌کند که فقط شما دو نفر دارید — سرور هرگز آن را نمی‌بیند.',
  link3T: 'نتایج می‌روند',
  link3D: 'هر هفته: چقدر برنامه‌ریزی کردید، چقدر تمام کردید، چقدر تمرکز کردید و سری که خودتان نوشتید.',
  link4T: 'آن‌ها می‌فهمند',
  link4D: 'نمودارهای دوازده هفته‌ی گذشته، و چند پرسشِ ارزشمند به‌جای انبوهی از جزئیات.',
  linkNote: 'فقط نتایج می‌روند. هرگز یک کار، هرگز یک یادداشت، هرگز دلیلی که خودتان نخواسته باشید.',
  linkGuardianT: 'دو بزرگسال، یک دانش‌آموز',
  linkGuardianD:
    'والد و مشاور دو نقش متفاوت‌اند. وقتی یکی از آن‌ها چیزی را برای دانش‌آموز تغییر می‌دهد، برنامه‌ریز خودِ دانش‌آموز خبر را به دیگری می‌رساند — باز هم رمز‌شده، باز هم درون برنامه.',

  authGoToApp: 'باز کردن برنامه‌ام',
  authOr: 'یا',
  authQuote1: 'دیگر سر تکالیف بحث نمی‌کنیم. فقط با هم هفته را نگاه می‌کنیم.',
  authQuote1By: 'والد یک نوجوان ۱۵ ساله',
  authQuote2: 'دلیل اینکه واقعاً ازش استفاده می‌کنم، همان کشوی خصوصی است.',
  authQuote2By: 'دانش‌آموز سال اول',
  authQuote3: 'یک کد، یک‌بار تایپ — بعد از آن هفته‌ها خودشان می‌رسند.',
  authQuote3By: 'مشاور، سال آخر',
  authBusy: 'در حال ایمن‌سازی برنامه‌تان',
  errBadCredentials: 'نام کاربری یا رمز عبور اشتباه است.',
  errTaken: 'این نام کاربری قبلاً گرفته شده.',
  errEmailTaken: 'این ایمیل قبلاً ثبت شده.',
  errNotConfigured: 'حساب‌ها روی این سرور هنوز راه‌اندازی نشده‌اند.',
  errNetwork: 'به سرور دسترسی نیست. اتصال‌تان را بررسی کنید.',
  errDeploymentGate:
    'این استقرار پشت صفحهٔ ورودِ سرویس میزبانی است و برنامه به API خودش دسترسی ندارد. Vercel Authentication را خاموش کنید (Project Settings ← Deployment Protection) یا دامنهٔ اصلی را باز کنید و دوباره تلاش کنید.',
  errApiMissing:
    'API حساب‌ها در این نشانی پاسخ نمی‌دهد. برنامه را همراه توابع api/ دوباره منتشر کنید یا دامنه‌ای که استفاده می‌کنید را بررسی کنید.',
  errLocalOnly:
    'این نسخهٔ برنامه‌ریز برای استفادهٔ آفلاین و بدون نشانی سرور ساخته شده است، پس ورود به حساب ممکن نیست. برنامه‌ریز شما همچنان روی همین دستگاه کار می‌کند.',
  errAppOriginRefused:
    'سرور پاسخ می‌دهد، اما درخواست‌های مبدأ خودِ برنامه را نمی‌پذیرد، پس ورود به حساب فعلاً ممکن نیست. سرورِ منتشرشده باید برنامه‌های نصب‌شده را در PLANNER_APP_ORIGINS فهرست کند (docs/APPS.md، بخش ۲)؛ در این فاصله چیزی روی این دستگاه از دست نمی‌رود.',
  errTemporaryAccounts:
    'حساب‌های این سرور فقط در حافظه نگه داشته می‌شوند، پس با هر بار راه‌اندازی دوباره همه از حساب خارج می‌شوند. برای نگه‌داشتن آن‌ها DATABASE_URL را تنظیم کنید.',
  errPasskeyCancelled: 'ورود با کلید عبور لغو شد.',
  errPasskeyUnsupported: 'کلید عبور به مرورگر به‌روز و اتصال امن نیاز دارد.',
  errPasskeyNoPrf: 'این مرورگر نمی‌تواند با کلید عبور قفل برنامه را باز کند؛ رمز عبور را وارد کنید.',
  errPasskeySession: 'ابتدا وارد شوید و بعد کلید عبور را اضافه کنید.',
  errPasskeyRejected: 'این کلید عبور برای این حساب پذیرفته نشد.',
  errRateLimited: 'تعداد تلاش‌ها زیاد است. یک دقیقه صبر کنید و دوباره تلاش کنید.',
  errUnexpectedResponse: 'سرور پاسخ غیرمنتظره‌ای داد. لطفاً دوباره تلاش کنید.',
  errUnknown: 'مشکلی پیش آمد. دوباره تلاش کنید.',
  errShortPassword: 'حداقل ۱۰ کاراکتر وارد کنید.',
  errNameRules: 'لطفاً نامی وارد کنید — تا ۶۰ کاراکتر.',
  errUsernameRules: 'نام کاربری باید ۳ تا ۲۴ نویسه داشته باشد و فقط شامل حروف انگلیسی، عدد یا زیرخط (_) باشد.',
  errEmailRules: 'آن ایمیل درست به نظر نمی‌رسد.',

  navBadge: 'جدید',
  heroBadge: 'با امکان برنامه‌ریزی مشترک',
  heroTitleLead: 'برنامه‌ریزی‌ای که',
  heroTitleAccent: 'روزتان را آرام نگه می‌دارد.',
  trustEncrypted: 'رمزنگاری سرتاسری',
  trustOffline: 'کار آفلاین',
  trustAds: 'بدون تبلیغ',
  heroNote: 'چیزی از دستگاه شما رمزنگاری‌نشده خارج نمی‌شود',
  strip1: 'رمزنگاری سرتاسری',
  strip2: 'روی همهٔ دستگاه‌ها آفلاین کار می‌کند',
  strip3: 'دانش‌آموز یک کشوی خصوصی دارد',
  strip4: 'هفته‌های بسته‌شده به خلاصه تبدیل می‌شوند',
  strip5: 'هر زمان بخواهید همه‌چیز را export کنید',
  appWinTitle: 'پلنر',
  appWinTab: 'امروز',
  heroStat1: '۷۸٪ این هفته',
  heroStat2: '۱۲ روز پیاپی',
  heroStat3: '۲ تغییر امروز',
  heroCardTitle: 'سارا تکلیف ریاضی را جابه‌جا کرد',
  heroCardWhy: 'امروز کارم زیاد است',
  heroCardMeta: 'همین الآن',
  roleTabPersonal: 'فقط خودم',
  roleTabStudent: 'دانش‌آموز',
  roleTabGuardian: 'سرپرست',
  switcherKicker: 'نقش‌ها را امتحان کنید',
  switcherTitle: 'سه در، یک برنامه',
  switcherSub: 'بین آن‌ها جابه‌جا شوید تا ببینید هر کس واقعاً چه می‌بیند.',
  previewPersonalTitle: 'فقط خودم',
  previewPersonalBody: 'نه صفحهٔ آرام. کارها، عادت‌ها، هدف‌ها، یادداشت‌ها و بینش‌ها — و هیچ‌کس دیگر در اتاق نیست.',
  previewPersonalTag: 'چیزی به اشتراک گذاشته نمی‌شود',
  previewStudentTitle: 'دانش‌آموز',
  previewStudentBody: 'همان برنامه، به‌علاوهٔ یک کارت که نشان می‌دهد چه کسی نگاه می‌کند و چه چیزی می‌بیند.',
  previewStudentTag: 'خودتان انتخاب می‌کنید',
  previewGuardianTitle: 'والد و مشاور',
  previewGuardianBody: 'یک فهرست به جای هفتهٔ خودتان. یک عدد، یک پاراگراف، و تغییرهای پشت آن‌ها.',
  previewGuardianTag: 'هفتهٔ او را می‌بینید',
  matrixKicker: 'چه کسی چه می‌بیند',
  matrixTitle: 'هیچ چیز تصادفی دیده نمی‌شود',
  matrixSub: 'هر خانهٔ این جدول انتخابی است که دانش‌آموز هنگام پذیرش پیوند انجام می‌دهد.',
  matrixColOwner: 'خود دانش‌آموز',
  matrixColParent: 'والد',
  matrixColAdvisor: 'مشاور',
  matrixRowPlan: 'کارها و برنامه‌ها',
  matrixRowHabit: 'عادت‌ها و رشته‌ها',
  matrixRowMood: 'ثبت حال‌وهوا',
  matrixRowNote: 'یادداشت‌ها و دفترچه',
  matrixRowFocus: 'زمان تمرکز',
  matrixRowDeadline: 'ضرب‌الاجل‌ها و درس‌ها',
  matrixYes: 'دیده می‌شود',
  matrixNo: 'هرگز دیده نمی‌شود',
  matrixOpt: 'فقط اگر به اشتراک بگذارید',
  dashKicker: 'پنل سرپرست',
  dashTitle: 'جلوی چشمتان ساخته می‌شود',
  dashS1T: 'یک عدد',
  dashS1D: 'وضعیت هفته در مقایسه با روند خود دانش‌آموز.',
  dashS2T: 'یک پاراگراف',
  dashS2D: 'چه تغییر کرده و چه باید کرد — نوشته‌شده از روی داده‌ها.',
  dashS3T: 'شش نمودار',
  dashS3D: 'فقط وقتی جزئیات می‌خواهید. هر کدام می‌گوید چرا مهم است.',
  aiApprove: 'تأیید',
  aiDecline: 'فعلاً نه',
  aiApproved: 'به برنامه اضافه شد',
  aiProposal: 'انتقال تکلیف ریاضی به پنجشنبه',
  aiProposalWhy: 'پنجشنبه دو ساعت آزاد دارد؛ سه‌شنبه شش ساعت پر است.',
  aiProposalBy: 'پیشنهاد هوش مصنوعی',
  retSliderLabel: 'نگهداری جزئیات کامل برای',
  retWeeks: 'هفته',
  retForever: 'همیشه',
  retAfter: 'بعد از بسته شدن هفته',
  retResults: 'فقط نتایج',
  retSize: 'حدود ۲۵ کیلوبایت تاریخچه در سال',
  statsKicker: 'در یک نگاه',
  statsTitle: 'قول‌های کوچک و عمل‌شده',
  stat1v: '۰',
  stat1l: 'تبلیغ، ردیاب یا فروش داده',
  stat2v: '۱۰۰٪',
  stat2l: 'محتوای برنامه رمزنگاری‌شده',
  stat3v: '۲۵ کیلوبایت',
  stat3l: 'تاریخچه در هر سال',
  stat4v: '۳',
  stat4l: 'راه برای بازگشت در صورت فراموشی',
  quotesKicker: 'حرف‌های اولیه',
  quotesTitle: 'چه می‌گویند',
  quote3: 'پیش از اینکه خودش بگوید می‌فهمم که خسته است. این همه‌چیز را عوض کرد.',
  quote3By: 'مادر یک دانشجوی سال اولی',
  footProduct: 'محصول',
  footCompany: 'مجموعه',
  footLegal: 'حقوقی',
  footTour: 'گشت‌وگذار',
  footPricing: 'قیمت‌ها',
  footChangelog: 'تازه‌ها',
  footAbout: 'درباره',
  footContact: 'تماس',
  footGithub: 'کد منبع',
  ctaBadge: 'شروع رایگان',
  platformsKicker: 'هر‌جا برنامه‌ریزی کنید',
  platformsTitle: 'روی گوشی، لپ‌تاپ و رایانهٔ رومیزی',
  platformsSub:
    'همان برنامه‌ریزِ آرام، نصب‌شده مثل یک برنامه. همه‌چیز روی دستگاه می‌ماند و فقط وقتی بخواهید همگام می‌شود.',
  platformsIphone: 'آیفون و آیپد',
  platformsIphoneNote:
    'در سافاری، «اشتراک‌گذاری ← افزودن به صفحهٔ اصلی» کل برنامه‌ریز را با آیکون خودش نصب می‌کند. نسخهٔ اپ‌استور به‌زودی.',
  platformsAndroid: 'اندروید',
  platformsAndroidNote:
    'فایل APK روی هر گوشی اندرویدی نصب می‌شود — شیائومی، ردمی، سامسونگ، پیکسل، هوآوی — و از همان‌جا به‌روز می‌شود. فروشگاه‌ها به‌زودی.',
  platformsWindows: 'ویندوز',
  platformsWindowsNote:
    'نصب‌کننده‌ای برای ویندوز ۱۰ و ۱۱ با میان‌بر منوی شروع، برای رایانه‌های Intel/AMD و ARM.',
  platformsMac: 'مک',
  platformsMacNote: 'فایل تصویری برای مک‌های Apple silicon و Intel.',
  platformsLinux: 'لینوکس',
  platformsLinuxNote: 'AppImage، deb. و rpm. — بدون مخزن و بدون دسترسی ریشه.',
  platformsDownloadWindows: 'بارگیری برای ویندوز',
  platformsDownloadMacArm: 'بارگیری برای Apple silicon',
  platformsDownloadMacIntel: 'بارگیری برای مک‌های Intel',
  platformsDownloadApk: 'بارگیری فایل APK',
  platformsDownloadLinuxAppImage: 'AppImage (x86_64)',
  platformsDownloadLinuxDeb: 'deb. (x86_64)',
  platformsDownloadLinuxRpm: 'rpm. (x86_64)',
  platformsDownloadLinuxArmImage: 'AppImage (ARM64)',
  platformsDownloadLinuxArmDeb: 'deb. (ARM64)',
  platformsSeeOptions: 'دیدن روش‌های نصب',
  platformsAllReleases: 'همهٔ نسخه‌ها',
  platformsDownloadFoot: 'فایل مستقیم از همین صفحه ذخیره می‌شود. میزبانی: GitHub Releases.',
  platformsSource: 'ساخت از کد منبع',
  platformsAppStore: 'اپ استور',
  platformsPlayStore: 'گوگل‌پلی',
  platformsWebInstead: 'استفاده از نسخهٔ وب',
  platformsHere: 'همین دستگاه',
  platformsAlsoOn: 'همچنین در',
  platformsFoot:
    'همهٔ نسخه‌ها یک برنامه‌ریزِ یکسان‌اند و نسخهٔ وب همیشه بدون نصب کار می‌کند.',
};

export type Lang = 'en' | 'fa';
export type CopyKey = keyof typeof en;

export const COPY: Record<Lang, Record<CopyKey, string>> = { en, fa };

export function isLang(value: string | null | undefined): value is Lang {
  return value === 'en' || value === 'fa';
}
