/**
 * Landing-page and auth copy in English and Persian.
 *
 * Deliberately NOT using `src/i18n.ts`: the i18n test scans every file under
 * `src/` for translatable string calls and fails when a Persian translation is
 * missing. The marketing site keeps its own typed dictionary instead, and
 * TypeScript checks the `fa` record below for completeness.
 */

export const en = {
  brand: 'Planner',
  tagline: 'calm daily planning',

  navHow: 'How it works',
  navRoles: 'Roles',
  navGuardians: 'For parents',
  navPrivacy: 'Privacy',
  navAI: 'AI',
  navSignIn: 'Sign in',
  navStart: 'Get started',
  navMenu: 'Menu',
  navClose: 'Close',
  themeToggle: 'Switch theme',
  langToggle: 'Switch language',

  heroKicker: 'Calm planning — alone, or together',
  heroTitle: 'A planner that keeps your day quiet.',
  heroSub:
    'Plan today, see your week, and shape the weeks ahead. Then, if you want it, let a parent or advisor walk beside you — seeing the plan, never the journal.',
  heroCta: 'Start planning — free',
  heroCta2: 'See how it works',
  heroTrust: 'End-to-end encrypted  ·  Works offline  ·  No ads, ever',
  heroDemoStudent: "Today — Sara's planner",
  heroDemoGuardian: "Guardian panel — Sara's week",

  stepsKicker: 'How it works',
  stepsTitle: 'Three steps, and nothing more',
  stepsSub: 'You can stop after step one. Most people do.',
  step1T: 'Pick your role',
  step1D: 'Just me, student, or parent & advisor. Every role lands in the same calm planner.',
  step2T: 'Plan your week',
  step2D: 'Tasks, habits, goals and notes in one place. Ask the AI to draft a week, then edit it.',
  step3T: 'Share what you choose',
  step3D: 'A student accepts a link and decides what each guardian sees. Private stays private.',

  rolesKicker: 'Roles',
  rolesTitle: 'One app, three ways to use it',
  rolesSub: 'Your personal planner never changes. Roles only add a door — you hold the key.',
  rolePersonalTag: 'Most people start here',
  rolePersonalT: 'Personal',
  rolePersonalD: 'Your day, your week, your notes. Nobody else sees a thing.',
  rolePersonalL1: 'Everything in the app today',
  rolePersonalL2: 'Encrypted sync across your devices',
  rolePersonalL3: 'Works offline, no account needed to peek',
  roleStudentT: 'Student',
  roleStudentD: 'Your plans, your report — and a private drawer that stays yours.',
  roleStudentL1: 'Daily, weekly and monthly plans',
  roleStudentL2: 'One-tap reasons when you change a plan',
  roleStudentL3: 'A private zone no guardian can open',
  roleGuardianT: 'Parent & advisor',
  roleGuardianD: 'See how they are really doing, and help without hovering.',
  roleGuardianL1: 'A roster, then one tap into a student',
  roleGuardianL2: 'Charts that explain themselves in one line',
  roleGuardianL3: 'Propose changes instead of silently editing',

  guardianKicker: 'The guardian panel',
  guardianTitle: 'One number, one paragraph, and six charts behind it',
  guardianSub:
    'No dashboard sprawl. You open a student and immediately see how their week is going and what to do about it.',
  guardianHeroLabel: 'This week',
  guardianHeroDelta: 'up 12% on last month',
  guardianNarrative:
    'Sara finished 78% of her plan, up 12% on last month. Her mood dipped on the three days she studied past 10pm. Thursday looks overloaded — consider moving one session.',
  chart1: 'Completion trend',
  chart1d: 'Against their own baseline, not a target.',
  chart2: 'Mood × load',
  chart2d: 'Spots burnout before grades do.',
  chart3: 'Week rhythm',
  chart3d: 'When they actually work.',
  chart4: 'Habit grid',
  chart4d: 'Rest days never break a streak.',
  chart5: 'Plan vs actual',
  chart5d: 'Shows chronic over-planning.',
  chart6: 'Balance',
  chart6d: 'Study, rest, chores, people.',
  guardianFeed: 'Changes this week',
  guardianFeed1Title: 'Moved Math homework to Thursday',
  guardianFeed1Why: 'Too much today',
  guardianFeed1Meta: 'Sara · 2 hours ago',
  guardianFeed2Title: 'Marked Chemistry lab as done',
  guardianFeed2Meta: 'Sara · yesterday',
  guardianFeed3Title: 'Cleared Saturday morning',
  guardianFeed3Why: 'Need help with this one',
  guardianFeed3Meta: 'Sara · Monday',

  studentKicker: 'The student side',
  studentTitle: 'Plans you can actually keep',
  studentSub: 'Simple on purpose: what you planned, what you did, and one button when it is too much.',
  studentL1: 'Daily, weekly and monthly plans in one view',
  studentL2: '"This is too much today" — the AI rebalances and lets your guardian know',
  studentL3: 'Guardian proposals arrive for your approval, never as silent edits',
  studentL4: 'A private drawer for notes nobody else reads',
  studentPrivate: 'Private',

  aiKicker: 'AI on both sides',
  aiTitle: 'It proposes. You decide.',
  aiSub: 'The AI never writes to a plan on its own. Everything it suggests lands as a draft you review.',
  aiStudentT: 'For students',
  aiStudentD:
    '“I cannot do today — make it lighter.” Back-plan a whole term from one exam date. Break a scary assignment into small steps.',
  aiGuardianT: 'For parents & advisors',
  aiGuardianD:
    '“Why is Amir slipping?” — a plain-language answer built from his week. Draft next week, or a note to his parents.',
  aiRule: 'Every suggestion says why. Nothing is applied without a person pressing yes.',

  privacyKicker: 'Privacy',
  privacyTitle: 'Encrypted so completely that we could not read your planner if we tried',
  privacySub: 'The server is a librarian, not a reader. It knows who you are and who you are linked to. Nothing else.',
  privacyCanTitle: 'We can see',
  privacyCan1: 'Your username and email',
  privacyCan2: 'Who you are linked to',
  privacyCan3: 'That a change happened — never what it was',
  privacyCannotTitle: 'We cannot see',
  privacyCannot1: 'A single task, note, mood or reason',
  privacyCannot2: 'Your password or your vault key',
  privacyCannot3: 'Anything after a week folds into results',
  retentionT: 'Your weeks become results, not archives',
  retentionD:
    'While a week is live, every change and reason is kept. After it closes, the detail rolls up into a small summary — a few hundred bytes — and the rest is gone. Your planner stops growing, and old data can never leak.',

  offlineKicker: 'Offline & installed',
  offlineTitle: 'It opens without a signal',
  offlineSub: 'Sign in once. After that your device is trusted and the planner works anywhere.',
  offlineL1: 'Edit, complete and plan with no connection',
  offlineL2: 'Install it on phone, tablet or desktop',
  offlineL3: 'Installed apps can notify you — the website keeps notifications inside the panel',

  faqKicker: 'Good to know',
  faqTitle: 'Questions people ask',
  faq1q: 'Do I need an account?',
  faq1a: 'Yes — one account keeps your planner yours across devices and makes linking to a guardian possible.',
  faq2q: 'Can a parent read my notes?',
  faq2a: 'Only notes you share. Anything you mark private is invisible to every guardian, with no override.',
  faq3q: 'What happens if I forget my password?',
  faq3a:
    'Approve the new sign-in from a device you already use, use a passkey, or enter the recovery key you saved at sign-up. In that order.',
  faq4q: 'Is this surveillance?',
  faq4a:
    'No. There is no screen monitoring, no location sharing, no leaderboards. Students see exactly who is watching and what they can see.',
  faq5q: 'How long is my data kept?',
  faq5a:
    'As long as you want. Live weeks keep full detail; closed weeks fold into small summaries you choose the window for.',

  ctaTitle: 'Start with today.',
  ctaSub: 'One quiet page. Add a task, check it off, and see how the week builds.',
  ctaButton: 'Create your planner',
  ctaSecondary: 'Talk to us first',

  footerRights: 'All rights reserved.',
  footerPrivacy: 'Privacy',
  footerTerms: 'Terms',
  footerSecurity: 'Security',
  footerStatus: 'Status',
  footerCode: 'Source',
  footerBuilt: 'Built for calm mornings.',

  authSignInTitle: 'Welcome back',
  authSignInSub: 'Sign in to open your planner.',
  authSignUpTitle: 'Create your planner',
  authSignUpSub: 'It takes about a minute. You can start with just you.',
  authName: 'Name',
  authNameHint: 'What your guardian or students will see',
  authUsername: 'Username or email',
  authUsernameOnly: 'Username',
  authEmail: 'Email (optional)',
  authEmailHint: 'For security alerts only — we never email your planner',
  authPassword: 'Password',
  authPasswordHint: 'At least 10 characters. Long and plain beats short and clever.',
  authShow: 'Show password',
  authHide: 'Hide password',
  authRemember: 'Remember this device',
  authRememberHint: 'So the planner opens offline',
  authPasskey: 'Sign in with a passkey',
  authPasskeyHint: 'Fingerprint, face, or your device PIN',
  authForgot: 'Forgot your password?',
  authNoAccount: 'New here?',
  authHasAccount: 'Already have a planner?',
  authCreate: 'Create an account',
  authSignInAction: 'Sign in',
  authContinue: 'Continue',
  authBack: 'Back',
  authStrengthWeak: 'Too short',
  authStrengthFair: 'Fair',
  authStrengthGood: 'Good',
  authStrengthStrong: 'Strong',
  authStepRole: 'How will you use Planner?',
  authStepRoleSub: 'This only adds a panel in Settings. Your planner stays exactly the same.',
  authRolePersonal: 'Just me',
  authRolePersonalD: 'A planner for my own days.',
  authRoleStudent: 'I am a student',
  authRoleStudentD: 'I want a parent or advisor to guide my plans.',
  authRoleGuardian: 'Parent or advisor',
  authRoleGuardianD: 'I want to support students or my children.',
  authRecoveryTitle: 'Save your recovery key',
  authRecoverySub:
    'This is the only way back in if you lose every device. We cannot reset it for you — nobody can. Copy it, download it, keep it somewhere safe.',
  authRecoveryCopy: 'Copy',
  authRecoveryCopied: 'Copied',
  authRecoveryDownload: 'Download',
  authRecoverySaved: 'I have saved my recovery key',
  authRecoveryView: 'You can view it again in Settings → Security.',
  authRecoveryWarn: 'Anyone with this key can open your planner.',
  authRecoverTitle: 'Get back in',
  authRecoverSub: 'Try the easiest one first.',
  authRecoverDevice: 'Approve from a device you already use',
  authRecoverDeviceD: 'We will ask your phone or laptop to confirm it is you.',
  authRecoverPasskey: 'Use a passkey',
  authRecoverPasskeyD: 'Fingerprint, face, or device PIN.',
  authRecoverKey: 'Enter your recovery key',
  authRecoverKeyD: 'The key you saved when you signed up.',
  authRecoverKeyLabel: 'Recovery key',
  authRecoverBack: 'Back to sign in',
  authTerms: 'I agree to the Terms and the Privacy Policy.',
  authDemoNote: 'Preview build — the forms are not connected to a server yet.',
  authGoToApp: 'Open my planner',
  authOr: 'or',
  authQuote1: 'I stopped arguing about homework. We just look at the week together.',
  authQuote1By: 'Parent of a 15-year-old',
  authQuote2: 'The private drawer is the reason I actually use it.',
  authQuote2By: 'Student, first year',

  navBadge: 'New',
  heroBadge: 'Now with shared planning',
  heroTitleLead: 'A planner that keeps',
  heroTitleAccent: 'your day quiet.',
  trustEncrypted: 'End-to-end encrypted',
  trustOffline: 'Works offline',
  trustAds: 'No ads, ever',
  heroNote: 'Nothing here leaves your device unencrypted',
  strip1: 'End-to-end encrypted',
  strip2: 'Works offline on every device',
  strip3: 'Students keep a private drawer',
  strip4: 'Closed weeks fold into results',
  strip5: 'Export everything, any time',
  appWinTitle: 'Planner',
  appWinTab: 'Today',
  heroStat1: '78% this week',
  heroStat2: '12-day streak',
  heroStat3: '2 changes today',
  heroCardTitle: 'Sara moved Math homework',
  heroCardWhy: 'Too much today',
  heroCardMeta: 'Just now',
  roleTabPersonal: 'Just me',
  roleTabStudent: 'Student',
  roleTabGuardian: 'Guardian',
  switcherKicker: 'Try the roles',
  switcherTitle: 'Three doors, one planner',
  switcherSub: 'Switch between them to see what each person actually sees.',
  previewPersonalTitle: 'Just me',
  previewPersonalBody: 'Nine quiet pages. Tasks, habits, goals, notes, insights — and nobody else in the room.',
  previewPersonalTag: 'Nothing is shared',
  previewStudentTitle: 'Student',
  previewStudentBody: 'The same planner, plus one card showing who is watching and what they can see.',
  previewStudentTag: 'You choose what is shared',
  previewGuardianTitle: 'Parent & advisor',
  previewGuardianBody: 'A roster instead of your own week. One number, one paragraph, and the changes behind them.',
  previewGuardianTag: 'You see their week',
  matrixKicker: 'Who sees what',
  matrixTitle: 'Nothing is visible by accident',
  matrixSub: 'Every cell here is a choice the student makes when they accept a link.',
  matrixColOwner: 'The student',
  matrixColParent: 'A parent',
  matrixColAdvisor: 'An advisor',
  matrixRowPlan: 'Tasks and plans',
  matrixRowHabit: 'Habits and streaks',
  matrixRowMood: 'Mood check-ins',
  matrixRowNote: 'Notes and journals',
  matrixRowFocus: 'Focus time',
  matrixRowDeadline: 'Deadlines and subjects',
  matrixYes: 'Visible',
  matrixNo: 'Never visible',
  matrixOpt: 'Only if shared',
  dashKicker: 'The guardian panel',
  dashTitle: 'It builds itself as you look',
  dashS1T: 'One number',
  dashS1D: 'How the week is going against their own baseline.',
  dashS2T: 'One paragraph',
  dashS2D: 'What changed, and what to do about it — written from the data.',
  dashS3T: 'Six charts',
  dashS3D: 'Only when you want the detail. Each one says why it matters.',
  aiApprove: 'Approve',
  aiDecline: 'Not now',
  aiApproved: 'Added to the plan',
  aiProposal: 'Move Math homework to Thursday',
  aiProposalWhy: 'Thursday has two free hours; Tuesday already has six.',
  aiProposalBy: 'Suggested by AI',
  retSliderLabel: 'Keep full detail for',
  retWeeks: 'weeks',
  retForever: 'Forever',
  retAfter: 'after the week closes',
  retResults: 'results only',
  retSize: 'about 25 KB per year of history',
  statsKicker: 'By the numbers',
  statsTitle: 'Small promises, kept',
  stat1v: '0',
  stat1l: 'Ads, trackers, or data sold',
  stat2v: '100%',
  stat2l: 'Of planner content encrypted',
  stat3v: '25 KB',
  stat3l: 'Of history kept per year',
  stat4v: '3',
  stat4l: 'Ways back in if you forget',
  quotesKicker: 'Early words',
  quotesTitle: 'What people say',
  quote3: 'I can see he is drowning before he tells me. That changed everything.',
  quote3By: 'Mother of a first-year student',
  footProduct: 'Product',
  footCompany: 'Company',
  footLegal: 'Legal',
  footTour: 'Take the tour',
  footPricing: 'Pricing',
  footChangelog: 'What is new',
  footAbout: 'About',
  footContact: 'Contact',
  footGithub: 'Source',
  ctaBadge: 'Free to start',
} as const;

export const fa: Record<keyof typeof en, string> = {
  brand: 'پلنر',
  tagline: 'برنامه‌ریزی آرام روزانه',

  navHow: 'چطور کار می‌کند',
  navRoles: 'نقش‌ها',
  navGuardians: 'برای والدین',
  navPrivacy: 'حریم خصوصی',
  navAI: 'هوش مصنوعی',
  navSignIn: 'ورود',
  navStart: 'شروع کنید',
  navMenu: 'منو',
  navClose: 'بستن',
  themeToggle: 'تغییر پوسته',
  langToggle: 'تغییر زبان',

  heroKicker: 'برنامه‌ریزی آرام — تنها یا با هم',
  heroTitle: 'برنامه‌ریزی‌ای که روزتان را آرام نگه می‌دارد.',
  heroSub:
    'امروز، هفته و هفته‌های پیشِ رو را برنامه بریزید. بعد، اگر خواستید، اجازه دهید والد یا مشاور کنارتان باشد — برنامه را ببیند، نه دفترچه‌تان را.',
  heroCta: 'شروع کنید — رایگان',
  heroCta2: 'ببینید چطور کار می‌کند',
  heroTrust: 'رمزنگاری سرتاسری  ·  کار آفلاین  ·  بدون تبلیغ',
  heroDemoStudent: 'امروز — برنامهٔ سارا',
  heroDemoGuardian: 'پنل سرپرست — هفتهٔ سارا',

  stepsKicker: 'چطور کار می‌کند',
  stepsTitle: 'سه قدم، و نه بیشتر',
  stepsSub: 'می‌توانید همان قدم اول تمام کنید. بیشتر افراد همین کار را می‌کنند.',
  step1T: 'نقش‌تان را انتخاب کنید',
  step1D: 'فقط خودم، دانش‌آموز، یا والد و مشاور. همه به یک برنامه‌ریز آرام می‌رسند.',
  step2T: 'هفته‌تان را برنامه بریزید',
  step2D: 'کارها، عادت‌ها، هدف‌ها و یادداشت‌ها در یک جا. از هوش مصنوعی بخواهید پیش‌نویس بزند، بعد خودتان ویرایش کنید.',
  step3T: 'هرچه می‌خواهید به اشتراک بگذارید',
  step3D: 'دانش‌آموز پیوند را می‌پذیرد و تعیین می‌کند هر سرپرست چه ببیند. خصوصی، خصوصی می‌ماند.',

  rolesKicker: 'نقش‌ها',
  rolesTitle: 'یک برنامه، سه شیوهٔ استفاده',
  rolesSub: 'برنامهٔ شخصی‌تان هرگز تغییر نمی‌کند. نقش‌ها فقط یک در اضافه می‌کنند — کلید دست خودتان است.',
  rolePersonalTag: 'بیشتر افراد از اینجا شروع می‌کنند',
  rolePersonalT: 'شخصی',
  rolePersonalD: 'روزتان، هفته‌تان، یادداشت‌هایتان. هیچ‌کس چیزی نمی‌بیند.',
  rolePersonalL1: 'همهٔ چیزی که امروز در برنامه هست',
  rolePersonalL2: 'همگام‌سازی رمزنگاری‌شده بین دستگاه‌ها',
  rolePersonalL3: 'آفلاین کار می‌کند',
  roleStudentT: 'دانش‌آموز',
  roleStudentD: 'برنامه‌ها و گزارش خودتان — و یک کشوی خصوصی که مال خودتان می‌ماند.',
  roleStudentL1: 'برنامه‌های روزانه، هفتگی و ماهانه',
  roleStudentL2: 'دلیل تغییر با یک لمس',
  roleStudentL3: 'یک بخش خصوصی که هیچ سرپرستی نمی‌تواند باز کند',
  roleGuardianT: 'والد و مشاور',
  roleGuardianD: 'ببینید واقعاً چطور پیش می‌روند، بدون اینکه بالای سرشان باشید.',
  roleGuardianL1: 'فهرست دانش‌آموزان، بعد یک لمس تا صفحهٔ هر کدام',
  roleGuardianL2: 'نمودارهایی که در یک خط خودشان را توضیح می‌دهند',
  roleGuardianL3: 'پیشنهاد تغییر، نه ویرایش پنهانی',

  guardianKicker: 'پنل سرپرست',
  guardianTitle: 'یک عدد، یک پاراگراف، و شش نمودار پشتِ آن',
  guardianSub: 'بدون شلوغی داشبورد. صفحهٔ دانش‌آموز را باز می‌کنید و همان لحظه می‌بینید هفته‌اش چطور است و چه باید کرد.',
  guardianHeroLabel: 'این هفته',
  guardianHeroDelta: '۱۲٪ بهتر از ماه قبل',
  guardianNarrative:
    'سارا ۷۸٪ برنامه‌اش را انجام داده، ۱۲٪ بهتر از ماه قبل. در سه روزی که بعد از ساعت ۱۰ شب درس خوانده حالش افت کرده. پنجشنبه سنگین به نظر می‌رسد — یکی از جلسه‌ها را جابه‌جا کنید.',
  chart1: 'روند انجام کارها',
  chart1d: 'در مقایسه با روند خودش، نه یک هدف تحمیلی.',
  chart2: 'حال × حجم کار',
  chart2d: 'فرسودگی را زودتر از نمره‌ها نشان می‌دهد.',
  chart3: 'ریتم هفته',
  chart3d: 'واقعاً کی کار می‌کند.',
  chart4: 'شبکهٔ عادت‌ها',
  chart4d: 'روز استراحت، رشته را نمی‌شکند.',
  chart5: 'برنامه در برابر واقعیت',
  chart5d: 'برنامه‌ریزی بیش‌از‌اندازه را نشان می‌دهد.',
  chart6: 'توازن',
  chart6d: 'درس، استراحت، خانه، آدم‌ها.',
  guardianFeed: 'تغییرهای این هفته',
  guardianFeed1Title: 'تکلیف ریاضی به پنجشنبه منتقل شد',
  guardianFeed1Why: 'امروز کارم زیاد است',
  guardianFeed1Meta: 'سارا · ۲ ساعت پیش',
  guardianFeed2Title: 'آزمایش شیمی انجام شد',
  guardianFeed2Meta: 'سارا · دیروز',
  guardianFeed3Title: 'صبح شنبه خالی شد',
  guardianFeed3Why: 'برای این یکی کمک می‌خواهم',
  guardianFeed3Meta: 'سارا · دوشنبه',

  studentKicker: 'سمت دانش‌آموز',
  studentTitle: 'برنامه‌هایی که واقعاً می‌شود نگه داشت',
  studentSub: 'به‌عمد ساده: چه برنامه ریختید، چه انجام دادید، و یک دکمه وقتی کار زیاد است.',
  studentL1: 'برنامه‌های روزانه، هفتگی و ماهانه در یک نما',
  studentL2: '«امروز زیاد است» — هوش مصنوعی دوباره تنظیم می‌کند و به سرپرست خبر می‌دهد',
  studentL3: 'پیشنهادهای سرپرست برای تأیید شما می‌آیند، نه به‌صورت ویرایش پنهان',
  studentL4: 'یک کشوی خصوصی برای یادداشت‌هایی که کسی نمی‌خواند',
  studentPrivate: 'خصوصی',

  aiKicker: 'هوش مصنوعی در هر دو سمت',
  aiTitle: 'پیشنهاد می‌دهد. تصمیم با شماست.',
  aiSub: 'هوش مصنوعی هیچ‌وقت خودش در برنامه چیزی نمی‌نویسد. هر پیشنهاد به‌صورت پیش‌نویس می‌آید تا شما بخوانید.',
  aiStudentT: 'برای دانش‌آموز',
  aiStudentD:
    '«امروز نمی‌توانم — سبک‌ترش کن.» از یک تاریخ امتحان، کل ترم را برنامه بریز. یک تکلیف ترسناک را به قدم‌های کوچک تقسیم کن.',
  aiGuardianT: 'برای والدین و مشاوران',
  aiGuardianD:
    '«چرا امیر عقب افتاده؟» — پاسخی ساده که از هفته‌اش ساخته شده. پیش‌نویس هفتهٔ بعد، یا یادداشتی برای والدینش.',
  aiRule: 'هر پیشنهاد دلیلش را می‌گوید. هیچ چیز بدون تأیید شما اعمال نمی‌شود.',

  privacyKicker: 'حریم خصوصی',
  privacyTitle: 'آن‌قدر رمزنگاری‌شده که اگر هم می‌خواستیم نمی‌توانستیم برنامه‌تان را بخوانیم',
  privacySub: 'سرور یک کتابدار است، نه خواننده. می‌داند شما کیستید و به چه کسی پیوند خورده‌اید. بس.',
  privacyCanTitle: 'می‌توانیم ببینیم',
  privacyCan1: 'نام کاربری و ایمیل شما',
  privacyCan2: 'به چه کسی پیوند خورده‌اید',
  privacyCan3: 'اینکه تغییری رخ داده — نه اینکه چه بوده',
  privacyCannotTitle: 'نمی‌توانیم ببینیم',
  privacyCannot1: 'حتی یک کار، یادداشت، حال یا دلیل',
  privacyCannot2: 'رمز عبور یا کلید گاوصندوق شما',
  privacyCannot3: 'چیزی که بعد از بسته شدن هفته به خلاصه تبدیل شده',
  retentionT: 'هفته‌های شما به نتیجه تبدیل می‌شوند، نه بایگانی',
  retentionD:
    'تا وقتی هفته زنده است، همهٔ تغییرها و دلیل‌ها نگه داشته می‌شود. وقتی بسته می‌شود، جزئیات در یک خلاصهٔ کوچک — چندصد بایت — جمع می‌شود و بقیه می‌رود. برنامه‌تان دیگر بزرگ نمی‌شود و دادهٔ قدیمی هرگز نشت نمی‌کند.',

  offlineKicker: 'آفلاین و نصب‌شده',
  offlineTitle: 'بدون آنتن هم باز می‌شود',
  offlineSub: 'یک بار وارد شوید. بعد از آن دستگاه‌تان معتمد است و برنامه هر جا کار می‌کند.',
  offlineL1: 'بدون اتصال، ویرایش و برنامه‌ریزی کنید',
  offlineL2: 'روی موبایل، تبلت یا رایانه نصبش کنید',
  offlineL3: 'برنامهٔ نصب‌شده می‌تواند آگاه‌سازی بفرستد — نسخهٔ وب آگاه‌سازی را داخل پنل نگه می‌دارد',

  faqKicker: 'بدانید',
  faqTitle: 'سؤال‌هایی که معمولاً پرسیده می‌شود',
  faq1q: 'به حساب کاربری نیاز دارم؟',
  faq1a: 'بله — یک حساب، برنامه‌تان را در همهٔ دستگاه‌ها مال شما نگه می‌دارد و پیوند با سرپرست را ممکن می‌کند.',
  faq2q: 'والدینم می‌توانند یادداشت‌هایم را بخوانند؟',
  faq2a: 'فقط یادداشت‌هایی که خودتان به اشتراک گذاشته‌اید. هرچه را خصوصی علامت بزنید برای همهٔ سرپرست‌ها نامرئی است.',
  faq3q: 'اگر رمز عبورم را فراموش کنم چه؟',
  faq3a:
    'ورود را از دستگاهی که قبلاً استفاده کرده‌اید تأیید کنید، از passkey استفاده کنید، یا کلید بازیابی را که هنگام ثبت‌نام ذخیره کردید وارد کنید. به همین ترتیب.',
  faq4q: 'این نظارت نیست؟',
  faq4a:
    'نه. پایش صفحه نداریم، مکان‌یابی نداریم، رتبه‌بندی نداریم. دانش‌آموز دقیقاً می‌بیند چه کسی نگاه می‌کند و چه چیزی می‌بیند.',
  faq5q: 'داده‌هایم چقدر نگه داشته می‌شود؟',
  faq5a:
    'هرقدر بخواهید. هفتهٔ جاری جزئیات کامل دارد؛ هفته‌های بسته‌شده به خلاصه‌های کوچکی تبدیل می‌شوند که بازه‌اش دست خودتان است.',

  ctaTitle: 'از امروز شروع کنید.',
  ctaSub: 'یک صفحهٔ آرام. یک کار اضافه کنید، انجامش را بزنید و ببینید هفته چطور ساخته می‌شود.',
  ctaButton: 'برنامه‌ام را بسازم',
  ctaSecondary: 'اول با ما صحبت کنید',

  footerRights: 'همهٔ حقوق محفوظ است.',
  footerPrivacy: 'حریم خصوصی',
  footerTerms: 'شرایط',
  footerSecurity: 'امنیت',
  footerStatus: 'وضعیت',
  footerCode: 'کد منبع',
  footerBuilt: 'ساخته‌شده برای صبح‌های آرام.',

  authSignInTitle: 'خوش برگشتید',
  authSignInSub: 'برای باز کردن برنامه‌تان وارد شوید.',
  authSignUpTitle: 'برنامه‌تان را بسازید',
  authSignUpSub: 'حدود یک دقیقه وقت می‌گیرد. می‌توانید فقط با «خودم» شروع کنید.',
  authName: 'نام',
  authNameHint: 'همان چیزی که سرپرست یا دانش‌آموزانتان می‌بینند',
  authUsername: 'نام کاربری یا ایمیل',
  authUsernameOnly: 'نام کاربری',
  authEmail: 'ایمیل (اختیاری)',
  authEmailHint: 'فقط برای هشدارهای امنیتی — برنامه‌تان را هرگز ایمیل نمی‌کنیم',
  authPassword: 'رمز عبور',
  authPasswordHint: 'حداقل ۱۰ کاراکتر. طولانی و ساده، بهتر از کوتاه و پیچیده است.',
  authShow: 'نمایش رمز',
  authHide: 'پنهان کردن رمز',
  authRemember: 'این دستگاه را به خاطر بسپار',
  authRememberHint: 'تا برنامه آفلاین هم باز شود',
  authPasskey: 'ورود با passkey',
  authPasskeyHint: 'اثر انگشت، چهره یا پین دستگاه',
  authForgot: 'رمز عبور را فراموش کرده‌اید؟',
  authNoAccount: 'تازه آمده‌اید؟',
  authHasAccount: 'قبلاً برنامه ساخته‌اید؟',
  authCreate: 'ساخت حساب',
  authSignInAction: 'ورود',
  authContinue: 'ادامه',
  authBack: 'بازگشت',
  authStrengthWeak: 'خیلی کوتاه',
  authStrengthFair: 'متوسط',
  authStrengthGood: 'خوب',
  authStrengthStrong: 'قوی',
  authStepRole: 'چطور از پلنر استفاده می‌کنید؟',
  authStepRoleSub: 'این فقط یک پنل به تنظیمات اضافه می‌کند. برنامه‌تان دقیقاً همان است که بود.',
  authRolePersonal: 'فقط خودم',
  authRolePersonalD: 'برنامه‌ای برای روزهای خودم.',
  authRoleStudent: 'دانش‌آموز هستم',
  authRoleStudentD: 'می‌خواهم والد یا مشاور برنامه‌هایم را راهنمایی کند.',
  authRoleGuardian: 'والد یا مشاور',
  authRoleGuardianD: 'می‌خواهم از دانش‌آموزان یا فرزندانم حمایت کنم.',
  authRecoveryTitle: 'کلید بازیابی‌تان را ذخیره کنید',
  authRecoverySub:
    'این تنها راه بازگشت است اگر همهٔ دستگاه‌هایتان را از دست بدهید. ما نمی‌توانیم آن را بازنشانی کنیم — هیچ‌کس نمی‌تواند. کپی کنید، دانلود کنید، جای امنی نگه دارید.',
  authRecoveryCopy: 'کپی',
  authRecoveryCopied: 'کپی شد',
  authRecoveryDownload: 'دانلود',
  authRecoverySaved: 'کلید بازیابی‌ام را ذخیره کردم',
  authRecoveryView: 'می‌توانید دوباره در تنظیمات ← امنیت ببینیدش.',
  authRecoveryWarn: 'هرکس این کلید را داشته باشد می‌تواند برنامه‌تان را باز کند.',
  authRecoverTitle: 'برگشتن به حساب',
  authRecoverSub: 'از ساده‌ترین راه شروع کنید.',
  authRecoverDevice: 'از دستگاهی که قبلاً استفاده کرده‌اید تأیید کنید',
  authRecoverDeviceD: 'از موبایل یا لپ‌تاپ‌تان می‌پرسیم که آیا خودتان هستید.',
  authRecoverPasskey: 'استفاده از passkey',
  authRecoverPasskeyD: 'اثر انگشت، چهره یا پین دستگاه.',
  authRecoverKey: 'کلید بازیابی را وارد کنید',
  authRecoverKeyD: 'کلیدی که هنگام ثبت‌نام ذخیره کردید.',
  authRecoverKeyLabel: 'کلید بازیابی',
  authRecoverBack: 'بازگشت به ورود',
  authTerms: 'شرایط و سیاست حریم خصوصی را می‌پذیرم.',
  authDemoNote: 'نسخهٔ نمایشی — فرم‌ها هنوز به سرور وصل نشده‌اند.',
  authGoToApp: 'باز کردن برنامه‌ام',
  authOr: 'یا',
  authQuote1: 'دیگر سر تکالیف بحث نمی‌کنیم. فقط با هم هفته را نگاه می‌کنیم.',
  authQuote1By: 'والد یک نوجوان ۱۵ ساله',
  authQuote2: 'دلیل اینکه واقعاً ازش استفاده می‌کنم، همان کشوی خصوصی است.',
  authQuote2By: 'دانش‌آموز سال اول',

  navBadge: 'جدید',
  heroBadge: 'با امکان برنامه‌ریزی مشترک',
  heroTitleLead: 'برنامه‌ریزی‌ای که',
  heroTitleAccent: 'روزتان را آرام نگه می‌دارد.',
  trustEncrypted: 'رمزنگاری سرتاسری',
  trustOffline: 'کار آفلاین',
  trustAds: 'بدون تبلیغ',
  heroNote: 'چیزی از دستگاه شما رمزنگاری‌نشده خارج نمی‌شود',
  strip1: 'رمزنگاری سرتاسری',
  strip2: 'روی همهٔ دستگاه‌ها آفلاین کار می‌کند',
  strip3: 'دانش‌آموز یک کشوی خصوصی دارد',
  strip4: 'هفته‌های بسته‌شده به خلاصه تبدیل می‌شوند',
  strip5: 'هر زمان بخواهید همه‌چیز را export کنید',
  appWinTitle: 'پلنر',
  appWinTab: 'امروز',
  heroStat1: '۷۸٪ این هفته',
  heroStat2: '۱۲ روز پیاپی',
  heroStat3: '۲ تغییر امروز',
  heroCardTitle: 'سارا تکلیف ریاضی را جابه‌جا کرد',
  heroCardWhy: 'امروز کارم زیاد است',
  heroCardMeta: 'همین الآن',
  roleTabPersonal: 'فقط خودم',
  roleTabStudent: 'دانش‌آموز',
  roleTabGuardian: 'سرپرست',
  switcherKicker: 'نقش‌ها را امتحان کنید',
  switcherTitle: 'سه در، یک برنامه',
  switcherSub: 'بین آن‌ها جابه‌جا شوید تا ببینید هر کس واقعاً چه می‌بیند.',
  previewPersonalTitle: 'فقط خودم',
  previewPersonalBody: 'نه صفحهٔ آرام. کارها، عادت‌ها، هدف‌ها، یادداشت‌ها و بینش‌ها — و هیچ‌کس دیگر در اتاق نیست.',
  previewPersonalTag: 'چیزی به اشتراک گذاشته نمی‌شود',
  previewStudentTitle: 'دانش‌آموز',
  previewStudentBody: 'همان برنامه، به‌علاوهٔ یک کارت که نشان می‌دهد چه کسی نگاه می‌کند و چه چیزی می‌بیند.',
  previewStudentTag: 'خودتان انتخاب می‌کنید',
  previewGuardianTitle: 'والد و مشاور',
  previewGuardianBody: 'یک فهرست به جای هفتهٔ خودتان. یک عدد، یک پاراگراف، و تغییرهای پشت آن‌ها.',
  previewGuardianTag: 'هفتهٔ او را می‌بینید',
  matrixKicker: 'چه کسی چه می‌بیند',
  matrixTitle: 'هیچ چیز تصادفی دیده نمی‌شود',
  matrixSub: 'هر خانهٔ این جدول انتخابی است که دانش‌آموز هنگام پذیرش پیوند انجام می‌دهد.',
  matrixColOwner: 'خود دانش‌آموز',
  matrixColParent: 'والد',
  matrixColAdvisor: 'مشاور',
  matrixRowPlan: 'کارها و برنامه‌ها',
  matrixRowHabit: 'عادت‌ها و رشته‌ها',
  matrixRowMood: 'ثبت حال‌وهوا',
  matrixRowNote: 'یادداشت‌ها و دفترچه',
  matrixRowFocus: 'زمان تمرکز',
  matrixRowDeadline: 'ضرب‌الاجل‌ها و درس‌ها',
  matrixYes: 'دیده می‌شود',
  matrixNo: 'هرگز دیده نمی‌شود',
  matrixOpt: 'فقط اگر به اشتراک بگذارید',
  dashKicker: 'پنل سرپرست',
  dashTitle: 'جلوی چشمتان ساخته می‌شود',
  dashS1T: 'یک عدد',
  dashS1D: 'وضعیت هفته در مقایسه با روند خود دانش‌آموز.',
  dashS2T: 'یک پاراگراف',
  dashS2D: 'چه تغییر کرده و چه باید کرد — نوشته‌شده از روی داده‌ها.',
  dashS3T: 'شش نمودار',
  dashS3D: 'فقط وقتی جزئیات می‌خواهید. هر کدام می‌گوید چرا مهم است.',
  aiApprove: 'تأیید',
  aiDecline: 'فعلاً نه',
  aiApproved: 'به برنامه اضافه شد',
  aiProposal: 'انتقال تکلیف ریاضی به پنجشنبه',
  aiProposalWhy: 'پنجشنبه دو ساعت آزاد دارد؛ سه‌شنبه شش ساعت پر است.',
  aiProposalBy: 'پیشنهاد هوش مصنوعی',
  retSliderLabel: 'نگهداری جزئیات کامل برای',
  retWeeks: 'هفته',
  retForever: 'همیشه',
  retAfter: 'بعد از بسته شدن هفته',
  retResults: 'فقط نتایج',
  retSize: 'حدود ۲۵ کیلوبایت تاریخچه در سال',
  statsKicker: 'در یک نگاه',
  statsTitle: 'قول‌های کوچک و عمل‌شده',
  stat1v: '۰',
  stat1l: 'تبلیغ، ردیاب یا فروش داده',
  stat2v: '۱۰۰٪',
  stat2l: 'محتوای برنامه رمزنگاری‌شده',
  stat3v: '۲۵ کیلوبایت',
  stat3l: 'تاریخچه در هر سال',
  stat4v: '۳',
  stat4l: 'راه برای بازگشت در صورت فراموشی',
  quotesKicker: 'حرف‌های اولیه',
  quotesTitle: 'چه می‌گویند',
  quote3: 'پیش از اینکه خودش بگوید می‌فهمم که خسته است. این همه‌چیز را عوض کرد.',
  quote3By: 'مادر یک دانشجوی سال اولی',
  footProduct: 'محصول',
  footCompany: 'مجموعه',
  footLegal: 'حقوقی',
  footTour: 'گشت‌وگذار',
  footPricing: 'قیمت‌ها',
  footChangelog: 'تازه‌ها',
  footAbout: 'درباره',
  footContact: 'تماس',
  footGithub: 'کد منبع',
  ctaBadge: 'شروع رایگان',
};

export type Lang = 'en' | 'fa';
export type CopyKey = keyof typeof en;

export const COPY: Record<Lang, Record<CopyKey, string>> = { en, fa };

export function isLang(value: string | null | undefined): value is Lang {
  return value === 'en' || value === 'fa';
}
